name: Build for ARM64 with QEMU on Debian

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build binaries for ARM64 with QEMU on Debian
    runs-on: ubuntu-latest  # 使用适合的操作系统环境，如 Ubuntu 或 Debian

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU for cross-architecture
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu qemu-user-static
          sudo update-binfmts --enable qemu-aarch64

      - name: Install Poetry
        run: pipx install poetry

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          poetry install

      - name: Build with Cx_Freeze
        run: |
          poetry run python setup.py build_exe -b dist

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: javsp-arm64
          path: dist
