name: CI 构建

on:
  push:
    branches:
      - master

jobs:
  qemu:
    name: 使用 QEMU 进行跨架构构建
    runs-on: ubuntu-latest  # 选择 Ubuntu 环境

    steps:
      # 检出代码
      - name: 检出代码
        uses: actions/checkout@v4

      # 设置 QEMU 环境
      - name: 设置 QEMU
        uses: docker/setup-qemu-action@v3

      # 设置 QEMU 仿真环境用于跨架构构建
      - name: 设置 QEMU 仿真
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu qemu-user-static
          sudo update-binfmts --enable qemu-aarch64  # 启用 ARM64 支持

      # 安装 Poetry（如果您有 Python 依赖）
      - name: 安装 Poetry
        run: pipx install poetry

      # 设置 Python 环境
      - name: 设置 Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 安装依赖
      - name: 安装依赖
        run: |
          poetry install

      # 构建二进制文件
      - name: 使用 Cx_Freeze 构建
        run: |
          poetry run python setup.py build_exe -b dist

      # 上传构建产物
      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: 构建产物-${{ github.sha }}
          path: dist
