name: Build ARM64 Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        run: |
          mkdir -p ~/.docker/cli-plugins
          curl -s https://github.com/docker/buildx/releases/download/v0.20.1/buildx-v0.20.1.linux-arm64 -o ~/.docker/cli-plugins/docker-buildx
          chmod +x ~/.docker/cli-plugins/docker-buildx

      - name: Configure APT sources to Aliyun mirrors
        run: |
          sudo echo "deb https://mirrors.aliyun.com/debian/ bookworm main contrib non-free" > /etc/apt/sources.list && \
          sudo echo "deb https://mirrors.aliyun.com/debian-security/ bookworm-security main contrib non-free" >> /etc/apt/sources.list && \
          sudo echo "deb https://mirrors.aliyun.com/debian/ bookworm-updates main contrib non-free" >> /etc/apt/sources.list && \
          sudo apt-get clean && \
          sudo apt-get update -y

      - name: Build ARM64 Docker image
        run: |
          docker buildx create --use
          docker buildx build --platform linux/arm64 -t my-python-app:latest .

      - name: Push Docker image to Docker Hub (optional)
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push my-python-app:latest
